### ISSUE TITLE
Make top endpoint generic

### ISSUE THREAD

**Issue by davidmparrott** [davidmparrott/DPSoftwareAPITest#17]
As a user, I want to be able to pass a tag(s) to the /top endpoint and get an top 10 list based on those params.

**Comment by lewallep** [comment]
I don't fully understand what you mean.  Am I right in thinking you want to pass parameters in a GET request to the top endpoint and select different fields to see the top ranks of those fields?  Such as, select the images with the most tags?  Or select a list of the highest scores?  Something like that.

**Comment by lewallep** [comment]
Per our discussion last night the idea of this issue is to allow the user to enter in a list of tags they want to find.  The list of documents returned will contain each tag passed in.  The documents containing all of the tags the user requests will be returned in a descending order of their highest score first.

A main objective of this issue is to perform this search in an efficient manner.

**Comment by lewallep** [comment]
### Possible solution

- Search the collection for the first tag in the list and return only those.

- From this query search it for the next tag.  Return only those to a new slice or map.

- Continue iterating down the list of query strings until finished.

- For a very large collection of photo URL's create a separate collections which has the following schema,
`[
 "_id": "word_goes_here"
 "doc_Ids": [ 5, 8474, 57463 ]
]`

This document keeps an array of all of the documents in the **photos** collections which have a tag that matches the _id field.

**Comment by lewallep** [comment]
using the $elemMatch did not work as expected.  You are able to pass multiple search terms however the search terms are meant to search different fields of arrays.  It is not possible to search the same field multiple times with $elemMatch.

At this time I am continuing with a single query on the tags field and only return the documents which contain the first tag in the query.  Then frontserve will perform an analysis on the returned slice of documents and continue to query each document with the next tag from the list of tags to find from the user.

At each tag it will dispose of the documents which do not contain one of the tags in the query.

**Comment by lewallep** [comment]
The topTags functionality is working as of now.  Testing is incomplete.  I will write the test drivers as a unit test to show multiple different types of edge cases in how this will be done.

**Comment by lewallep** [comment]
Closing this issue.  Opening a new Issue to test this functionality for correctness.
