### ISSUE TITLE
frontserve.go does not put a score field in the response

### ISSUE THREAD

**Issue by lewallep** [davidmparrott/DPSoftwareAPITest#25]
Detected a problem on the remote dev environment (davidmparrott.com) where frontserve.go did not send a score or tags in the the response to the client when hitting the /images endpoint.  

The endpoint /test in frontserve.go did serve up a proper response.

Assigning to David as he is working on the solution and a potential fix has been pushed out.

**Comment by davidmparrott** [comment]
This has been resolved. ScrambleQueue() was not working correctly. The return queue wasn't being assigned to url_queue in UrlQueue().
