### ISSUE TITLE
Check to see if image URL is still valid in the client

### ISSUE THREAD

**Issue by lewallep** [davidmparrott/DPSoftwareAPITest#8]
In index.html check to see if the image URL received is still pointing to a valid image.  If a 404 error is received send a signal to the database frontserve.go to have the image removed from the database using a DELETE request.

This will all be done asyncronously.  There is a follow up issue to create a simple timed service in main.go to run a check for any 404 errors from the URL's as a first check.

**Comment by lewallep** [comment]
This was attempted to be implemented in the backend in main.go and it was unsuccessful as it generated a DDoS attack flag from flickr.  Or at least this is my hypothesis.  

To combat this we will move the check of the Url for a 404 to the client.  If the client receives a 404 response the client will set this field in the database.

**Comment by lewallep** [comment]
For the time being the document which is found to have a url which returns a 404 will not be deleted.  This will be done to maintain all of the user data inserted into these documents.

**Comment by davidmparrott** [comment]
This feature, which will implement a retry when the client gets a 404 for an image, will eventually be complimented by a maintenance utility that will periodically check images which sent back a 404 response when requested. 

To clarify, when Flickr sends a 404 in response to a request for an image, the client will request a new image from the queue. 

In the future, the client will send a modification request to frontserve which will indicate that a 404 response was received when requesting this image. A maintenance utility will be built to analyze documents that have the 404 indicator, applying some heuristic analysis that is TBD, and decide whether to remove the document permanently.

**Comment by lewallep** [comment]
This is being closed for now as the preliminary version is done.  The logic only skips over an image which does not return a 200 status code when the image is fully loaded.  

The plan for the next version will be to rewrite the page for different logic utilizing a static layout for the main page and logic will run recursively and cache one image ahead and then test the next image until it is ready.
