### ISSUE TITLE
Check for 404 errors from database URL's in main.go

### ISSUE THREAD

**Issue by lewallep** [davidmparrott/DPSoftwareAPITest#9]
Write a function to go through the database and check to see if there are any 404 errors generated when the URL's are checked to see if the images they are referring to still exist.  This can be run as an asynchronous routine inside of main.go which can be run at the same time on the same clock.  Since this service will be run at off peak hours and only once every 24 hours independent of the load on the database it does not appear to have any scaling issues for the foreseeable future.

**Comment by lewallep** [comment]
Moving the validation of the Urls to the clients.  If we run a batch process that just throws out the Get requests as quickly as we can to the service, in this case flickr, then the program gets flagged as a DDoS attack.

**Comment by davidmparrott** [comment]
re-opening this to take another stab at doing this in main.go

**Comment by davidmparrott** [comment]
Added checking to main.go but at the present it just prints a list of document IDs that got  404 to STDOUT. This process runs very slow due to rate limiting by Flickr. Had to add a 1 second sleep between calls in order to get this to complete.

**Comment by davidmparrott** [comment]
This approach will not be feasible for very long. At our current rate of about 497 new documents a day it will only take 174 days until the number of documents we need to check is greater than the number of seconds in a day. Sure, we could run this once a week but that still makes this an insanely long running job. The only viable solution is having the client pull another URL object off the queue and update the document to have a 404 tag or some other indicator that there was a problem. 

If we only look for documents with the 404 tag and re-check them once a day I think we can maintain a manageable work load. The logic I put in can be re-used to check the 404-tagged documents so I'm leaving it in main.go for future reference
